services:
  client-api:
    container_name: "client-api"   
    image: ${DOCKER_REGISTRY-}iipg2244/client-api
    build:
      context: ".."
      dockerfile: "./server/Client.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_URLS=https://+:44301;http://+:8001
      - ASPNETCORE_HTTPS_PORT=44301
      - ASPNETCORE_HTTP_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./Certificates/client-api.pfx
    ports:
      - "44301:44301"
      - "8001:8001"
    depends_on:
      grpc-api:
        condition: service_started
  grpc-api:
    container_name: "grpc-api"   
    image: ${DOCKER_REGISTRY-}iipg2244/grpc-api
    build:
      context: ".."
      dockerfile: "./server/Grpc.API/Dockerfile"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
      - ASPNETCORE_URLS=https://+:44302;http://+:8002
      - ASPNETCORE_HTTPS_PORT=44302
      - ASPNETCORE_HTTP_PORT=8002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./Certificates/grpc-api.pfx
    ports:
      - "44302:44302"
      - "8002:8002"